In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('C:\\Users\\aleks\\Desktop\\courseML\\08-Linear-Regression-Models\\Advertising.csv')
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [5]:
X = df.drop('sales',axis=1)
y = df['sales']

In [83]:
from sklearn.preprocessing import PolynomialFeatures
poly_convert = PolynomialFeatures(degree=3,include_bias= False)
poly_features = poly_convert.fit_transform(X)
poly_features[0]

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)


In [21]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [22]:
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[ 0.49300171, -0.33994238,  1.61586707, ..., -0.16360242,
         0.54694754,  1.37075536],
       [ 1.61337153,  1.32852213,  1.90079242, ...,  2.63236858,
         2.6297449 ,  1.95593378],
       [-0.84811893, -1.58789957, -1.02319564, ..., -0.72634944,
        -0.61593941, -0.54133745],
       ...,
       [ 1.04606563, -1.30982215,  0.27064572, ..., -0.71065643,
        -0.53420112, -0.20690952],
       [ 0.74817069,  0.03987068, -1.26608283, ..., -0.66805936,
        -0.61031703, -0.54616941],
       [ 0.13813882,  0.55533126,  1.01799092, ...,  0.61006767,
         0.67881488,  0.45425942]])

In [23]:
from sklearn.linear_model import Ridge
ridge_model = Ridge(alpha=10)
ridge_model.fit(X_train,y_train)
test_predictions = ridge_model.predict(X_test)

In [24]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.5774404204714172

In [25]:
MSE = np.sqrt(mean_squared_error(y_test, test_predictions))
MSE

0.8946386461319674

In [26]:
from sklearn.linear_model import RidgeCV

In [40]:
ridge_cv_model = RidgeCV(alphas=(0.1,0.05,0.001), scoring = 'neg_mean_squared_error')

In [41]:
ridge_cv_model.fit(X_train, y_train)

RidgeCV(alphas=array([0.1  , 0.05 , 0.001]), scoring='neg_mean_squared_error')

In [42]:
ridge_cv_model.alpha_

0.001

In [43]:
from sklearn.metrics import SCORERS
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted'])

In [45]:
test_predictions = ridge_cv_model.predict(X_test)
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.4124212416448587

In [46]:
MSE = np.sqrt(mean_squared_error(y_test, test_predictions))
MSE

0.5805475447323761

In [50]:
ridge_cv_model.coef_

array([  7.15817084,   0.46793837,   0.26771354, -10.30058521,
         5.11206443,  -1.72753762,  -1.298858  ,   0.80100652,
         0.44727661,   4.92676681,  -1.52639571,   1.50101202,
         0.39103713,  -0.32659488,   0.01429201,   0.73845434,
        -0.32580988,  -0.24604891,  -0.28024833])

In [ ]:
#LASSO

In [67]:
from sklearn.linear_model import LassoCV
lasso_cv_model = LassoCV(eps=0.001,n_alphas=100, cv=5, max_iter = 1000000)
lasso_cv_model.fit(X_train, y_train)
lasso_cv_model.alpha_

0.004943070909225827

In [68]:
test_predictions = lasso_cv_model.predict(X_test)

In [69]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.43350346185900673

In [70]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))
RMSE

0.6063140748984032

In [71]:
lasso_cv_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

In [ ]:
#ElasticNet

In [72]:
from sklearn.linear_model import ElasticNetCV

In [73]:
elastic_cv_model = ElasticNetCV(l1_ratio = [.1,.5,.7,.9,.95,.99,1], eps = 0.001, n_alphas=100, max_iter=100000)

In [74]:
elastic_cv_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=100000)

In [75]:
elastic_cv_model.l1_ratio_ # все свелось в лассо регрессию

1.0

In [76]:
elastic_cv_model.alpha_

0.004943070909225827