Реализация зависимости y = 2*x1 + x2 + 1

In [155]:
import numpy as np
X = np.array([[1,2],[2,3],[3,4],[4,5],[5,6],[6,7],[7,8]])
y = np.array([[5,8,11,14,17,20,23]])
X[:,1],y

(array([2, 3, 4, 5, 6, 7, 8]), array([[ 5,  8, 11, 14, 17, 20, 23]]))

In [99]:
from keras.layers import Dense
from keras.models import Sequential
import tensorflow as tf
tf.random.set_seed(0)

model = Sequential([
    Dense(1,input_shape=(2,), activation='linear')
])
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_5 (Dense)             (None, 1)                 3         
                                                                 
Total params: 3 (12.00 Byte)
Trainable params: 3 (12.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [100]:
w1_w2, w0 = model.get_weights()


In [101]:
w1 = w1_w2[0][0]
w2 = w1_w2[1][0]
w0 = w0[0]

In [102]:
w1 = np.array([[w1],[0]])
w2 = np.array([[0],[w2]])

In [103]:
w1,w2

(array([[1.31544626],
        [0.        ]]),
 array([[ 0.        ],
        [-1.20179784]]))

In [104]:
X[:1]

array([[1, 2]])

In [105]:
model.predict(X[:1])

1/1 [==============================] - 0s 52ms/step


array([[-1.0881494]], dtype=float32)

In [169]:
def mse_error(X, w1, w2, w0, y):
  y_pred = (np.dot(X, w1) + np.dot(X, w2) + w0).reshape(1,7)
  return np.sum((y - y_pred)**2)/len(y)

def grad_mse_error(X, w1, w2, w0, y):
  y_pred = (np.dot(X, w1) + np.dot(X, w2) + w0).reshape(1,7)
  grad = dict([('grad_w1', 2/len(y) * np.sum(np.dot(y - y_pred,(-X[:,0])))),
              ('grad_w2', 2/len(y) * np.sum(np.dot(y - y_pred,(-X[:,1])))),
              ('grad_w0', 2/len(y) * np.sum((y - y_pred) * (-1)))])
  return grad

In [168]:
grad = grad_mse_error(X, w1,w2,w0,y)
grad

{'grad_w1': -987.4791231155396,
 'grad_w2': -1193.9399816989899,
 'grad_w0': -206.46085858345032}

In [228]:
learning_rate = 0.0001

In [166]:
next_w1 = w1[0][0] - learning_rate * grad['grad_w1']
next_w1

11.190237488746643

In [159]:
w1[0][0]

1.3154462575912476

In [238]:
def grad_descent(n_iter, w1,w2,w0):
  for i in range(n_iter):
    curr_w1 = w1
    curr_w2 = w2
    curr_w0 = w0

    grad = grad_mse_error(X, curr_w1,curr_w2,curr_w0,y)

    w1 = curr_w1[0][0] - learning_rate * grad['grad_w1']
    w2 = curr_w2[1][0] - learning_rate * grad['grad_w2']
    w0 = curr_w0 - learning_rate * grad['grad_w0']

    w1 = np.array([[w1],[0]])
    w2 = np.array([[0],[w2]])

    print(f"\n---iter {i}:\n {mse_error(X, w1, w2, w0, y)}\n---w1: {w1[0][0]}\n---w2: {w2[1][0]}\n---w0: {w0}\n")
  return w1[0][0],w2[1][0],w0


In [239]:
optimal_w1, optimal_w2, optimal_w3 = grad_descent(14000,w1,w2,w0)

Выходные данные были обрезаны до нескольких последних строк (5000).
---w0: 1.1625023431029256


---iter 13286:
 0.00025511986513028213
---w1: 2.1787551861643273
---w2: 0.8240167753905467
---w0: 1.162505689796895


---iter 13287:
 0.00025494762275211284
---w1: 2.1787530454357413
---w2: 0.8240179802259909
---w0: 1.1625090353609253


---iter 13288:
 0.00025477549666208835
---w1: 2.178750905429926
---w2: 0.8240191846546483
---w0: 1.162512379795398


---iter 13289:
 0.0002546034867817865
---w1: 2.178748766146638
---w2: 0.8240203886766563
---w0: 1.1625157231006944


---iter 13290:
 0.0002544315930328016
---w1: 2.178746627585632
---w2: 0.8240215922921521
---w0: 1.1625190652771957


---iter 13291:
 0.00025425981533665784
---w1: 2.178744489746666
---w2: 0.8240227955012731
---w0: 1.162522406325283


---iter 13292:
 0.0002540881536150214
---w1: 2.178742352629495
---w2: 0.8240239983041565
---w0: 1.1625257462453373


---iter 13293:
 0.0002539166077895552
---w1: 2.1787402162338756
---w2: 0.824025200

оптимальные веса были найдены!!!

In [240]:
optimal_w1, optimal_w2, optimal_w3

(2.177398465391904, 0.8247803590064157, 1.1646259941851842)